export default {
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",
    POPULAR_REFRESH:"POPULAR_REFRESH",//刷新的时候
    LOAD_POPULAR_FAIL:"LOAD_POPULAR_FAIL",
    LOAD_POPULAR_SUCCESS:"LOAD_POPULAR_SUCCESS",
    PULL_LOAD_SUCCESS:"PULL_LOAD_SUCCESS",
    PULL_LOAD_FAIL:"PULL_LOAD_FAIL"
}